name: First Workflow

run-name: ${{ github.actor }}
on: push
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "display data"
  job2: 
    runs-on: windows-latest
    steps:
      - name: Read
        run: echo "hey!"
