name: GitHub Context and Environment Variables

on: 
  push: 
  workflow_dispatch:

jobs:
  echo-context:
    runs-on: ubuntu-latest
    steps: 
      - name: Display info
        run: |
          echo "Event name is ${{ github.event_name }}"
          echo "Ref is ${{ github.ref }}"
          echo "SHA is ${{ github.sha }}"
          echo "Actor is ${{ github.actor }}"
          echo "Run Id is ${{ github.run_id }}"
          echo "Variable value is ${{ vars.MY_VAR }}"
