name: Log GitHub Context and Set Environment Variables

on:
  push:
    branches:
      - main
      - develop

jobs:
  log-context-and-set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log GitHub context values
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event Name: ${{ github.event_name }}"

      - name: Set environment variable GIT_BRANCH
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "GIT_BRANCH=main" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "GIT_BRANCH=develop" >> $GITHUB_ENV
          else
            echo "GIT_BRANCH=other" >> $GITHUB_ENV
          fi

      - name: Print GIT_BRANCH
        run: echo "GIT_BRANCH is $GIT_BRANCH"
