name: Simple Deployment

on: 
 push: 
  branches:
    - main
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      -name: Set DEPLOY_ENV based on branch
      run: |
        if [["${{ github.ref }}" == "ref/heads/main" ]]; then
          echo "DEPLOY_ENV=production" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "ref/head/develop" ]]
          echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
        fi

     -name: Log the DEPLOY_ENV
      run: echo "Deploying to ${{ env.DEPLOY_ENV }}"
      
